#!/bin/bash

if [ -d /root ]
then
echo ""
else
mkdir /root
fi
cd /root/
if [[ -e /bin/instalacao1 ]]; then
instalar
exit
sleep 4s
else
 if [[ -e /bin/instalacao2 ]]; then
instalar
exit
sleep 4s
else
  if [[ -e /bin/instalacao3 ]]; then
instalar
exit
sleep 4s
else
   if [[ -e /bin/instalacao4 ]]; then
instalar
exit
sleep 4s
else
echo " "
clear
   fi
  fi
 fi
fi
clear
sleep 1s
echo -e "\033[1;31mAtencion lea atentamente antes de instalar este scritp, distribuido para Costa Rica ssh\033[0m"
echo -e "\033[1;36mEs responsabilidad del Usuario el uso que le de a este programa!\033[1;31m"
read -p"Precione Enter para seguir "
echo -e "\033[1;36mESTE SCRIPT FUE PROBADO EN SISTEMAS 
-----------------
DEBIAN
UBUNTU
-----------------
PUEDE HABER IMCOMPATIBILIDAD EN OTROS SISTEMAS!!!\033[1;31m"
read -p"Precione Enter para seguir"
echo -e "\033[0m"
sleep 1s
echo -e "\033[1;31mA El sistema comnenzara la instalacion en 3 SEGUNDOS...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36mCOMECANDO...\033[0m"
sleep 1s
echo -e "\033[1;36mPreparando Descarga...\033[0m"
apt-get upgrade -y 1>/dev/null 2>/dev/null
echo  -e "\033[1;32m"
apt-get install zip -y
sleep 1s
echo  -e "\033[0m"
echo -e "\033[1;36mRecibiendo Descarga...\033[0m"
cd /root/
sleep 1s
wget -O manager https://www.dropbox.com/s/y71axcii0tmvr8c/admmanager.zip?dl=0 -o /dev/null
sleep 4s
echo -e "\033[1;36mDescomprimiendo Archivos...\033[0m"
sleep 4s
echo -e "\033[1;36mDescomprimiendo Archivos...\033[0m"
echo  -e "\033[1;32m"
unzip /root/manager
echo  -e "\033[0m"
sleep 4s
echo -e "\033[1;36mArchivos extraidos!...\033[0m"
sleep 4s
echo -e "\033[1;36mDando permiso a los archivos...\033[0m"
mv -f /root/admmanager/* /bin/
chmod  -R 777 /bin/*
sleep 5s
echo -e "\033[1;36mInciando!!!...\033[0m"
sleep 4s
echo -e "\033[1;36mIniciando instalador\033[0m"
sleep 4s
echo -e "\033[1;36mEspere un Momento...\033[0m"
rm -rf /root/manager*
sleep 1s
rm -rf /root/admmanager*
sleep 1s
rm -rf /root/inst*
sleep 1s
echo -e "\033[1;36mEspere un Momento......\033[0m"
sleep 2s
echo -e "\033[1;31mLa instalacion Inicia en 3 segundos...\033[0m"
echo -e "\033[1;36m3...\033[0m"
sleep 1s
echo -e "\033[1;36m2...\033[0m"
sleep 1s
echo -e "\033[1;36m1...\033[0m"
sleep 1s
echo -e "\033[1;36m...\033[0m"
sleep 1s
echo -e "\033[1;36mIniciando...\033[0m"
instalar
sleep 2s
clear
exit
